# Generated by Django 4.0 on 2022-11-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_created_time_account_expired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='remaining_days',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
