# Generated by Django 4.0 on 2023-01-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_expiration_account_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_time',
            field=models.DateField(default='1401-10-16'),
        ),
        migrations.AlterField(
            model_name='account',
            name='modified_time',
            field=models.DateField(default='1401-10-16'),
        ),
    ]
