# Generated by Django 4.0 on 2022-11-07 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('web', models.CharField(max_length=35, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieDistributer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_rate', models.BigIntegerField(null=True)),
                ('distributers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='distributer.distributer')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributer', to='movie.movie')),
            ],
        ),
    ]
