# Generated by Django 4.0 on 2022-11-08 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_number',
            field=models.UUIDField(default=uuid.UUID('d6a2f927-52f3-4e76-9cee-eb149361c4ac'), unique=True, verbose_name='invoice number'),
        ),
    ]
