# Generated by Django 4.0 on 2022-11-08 14:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_alter_payment_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_number',
            field=models.UUIDField(default=uuid.UUID('7d42402e-7c42-4c6e-b695-79a01f6941ed'), unique=True, verbose_name='invoice number'),
        ),
    ]
