# Generated by Django 4.0 on 2022-11-10 09:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_alter_payment_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_number',
            field=models.UUIDField(default=uuid.UUID('943230d2-7753-411d-a49e-e0ecb9685e6e'), unique=True, verbose_name='invoice number'),
        ),
    ]
