# Generated by Django 4.0 on 2022-11-10 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_alter_payment_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_number',
            field=models.UUIDField(default=uuid.UUID('8a5f74ed-4944-4f88-a907-dc50691ed6e2'), unique=True, verbose_name='invoice number'),
        ),
    ]
