# Generated by Django 4.0 on 2022-11-10 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_alter_payment_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_number',
            field=models.UUIDField(default=uuid.UUID('22fefbca-bcb8-454a-bbb0-b95b7d9702f1'), unique=True, verbose_name='invoice number'),
        ),
    ]
