# Generated by Django 4.0 on 2022-11-10 10:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0010_alter_payment_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_number',
            field=models.UUIDField(default=uuid.UUID('7c4bf938-4585-4c2c-8aa3-9f592f96531a'), unique=True, verbose_name='invoice number'),
        ),
    ]
