# Generated by Django 4.0 on 2022-11-10 11:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0011_alter_payment_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_number',
            field=models.UUIDField(default=uuid.UUID('50a33281-0129-47b1-8f66-4928df6993bb'), unique=True, verbose_name='invoice number'),
        ),
    ]
