# Generated by Django 4.0 on 2022-11-10 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0012_alter_payment_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_number',
            field=models.UUIDField(default=uuid.UUID('74a0019d-eea4-4c37-8a4b-66a99d200dab'), unique=True, verbose_name='invoice number'),
        ),
    ]
