# Generated by Django 4.0 on 2022-11-23 10:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0014_alter_payment_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_number',
            field=models.UUIDField(default=uuid.UUID('16a9ccd3-c738-4cf5-b361-1290960a4d3d'), unique=True, verbose_name='invoice number'),
        ),
    ]
