# Generated by Django 4.0 on 2022-11-23 12:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0015_alter_payment_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_number',
            field=models.UUIDField(default=uuid.UUID('feb90e00-1101-4c69-b1ce-b0598c8d976b'), unique=True, verbose_name='invoice number'),
        ),
    ]
