# Generated by Django 4.0 on 2023-01-06 12:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0017_alter_payment_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_number',
            field=models.UUIDField(default=uuid.UUID('3556024b-50a0-474c-bfa8-538811640d26'), unique=True, verbose_name='invoice number'),
        ),
    ]
