# Generated by Django 4.0 on 2022-11-07 14:26

from django.db import migrations, models
import django.db.models.deletion
import khayyam.jalali_datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('year', models.IntegerField(blank=True)),
                ('rate', models.FloatField(blank=True)),
                ('age_res', models.CharField(max_length=10)),
                ('summary', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('awards', models.CharField(max_length=32)),
                ('register_date', models.DateTimeField(default=khayyam.jalali_datetime.JalaliDatetime.now)),
                ('modify_date', models.DateTimeField(default=khayyam.jalali_datetime.JalaliDatetime.now)),
                ('platform', models.CharField(blank=True, max_length=13)),
                ('quality', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True)),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actrs_movies', to='movie.actor')),
                ('director_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='movie.director')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='movie.genre')),
            ],
        ),
        migrations.CreateModel(
            name='MovieImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='MovieImages/')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='GenreMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moviegenres', to='movie.genre')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genresmovies', to='movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='DirMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directors', to='movie.director')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directorsmovies', to='movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='ActorMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moviesactors', to='movie.actor')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actorsmovies', to='movie.movie')),
            ],
        ),
    ]
