# Generated by Django 4.0 on 2022-11-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_comment_quality_remove_movie_actor_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre_id',
        ),
    ]
