# Generated by Django 4.0 on 2022-11-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_movie_genre_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviequality',
            name='Download_links',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
