# Generated by Django 4.0 on 2022-11-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_comment_movie_delete_moviecomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default='1401-09-06 13:47:57.967862'),
        ),
    ]
