# Generated by Django 4.0 on 2023-01-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_trailer_alter_comment_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default='1401-10-16 13:16:30.065962'),
        ),
    ]
