# Generated by Django 4.0 on 2022-11-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='Profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
