# Generated by Django 4.0 on 2022-11-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_myuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='Profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_pic/'),
        ),
    ]
